name: Test SSH to GCP VM

on:
  workflow_dispatch  # Lets you run this manually in the GitHub Actions tab

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CUSTOM_GCP_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} "echo '✅ SSH successful! Hostname: ' && hostname"
